name: Distribute Exe

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - uses: actions/checkout@v3
    - name: Set ENV
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Add powerpc-unknown-linux-gnu
      run: rustup target add --toolchain stable powerpc-unknown-linux-gnu
      working-directory: randomprime
    - uses: Swatinem/rust-cache@v2

    - name: Cargo Build
      run: cargo build --release
      working-directory: randomprime

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: randomprime_patcher.exe
        path: randomprime\target\release\randomprime_patcher.exe
        if-no-files-found: error

  attach:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: montudor/action-zip@v1
      with:
        args: zip -q randomprime_patcher-${{ env.RELEASE_VERSION }}.zip randomprime\target\release\randomprime_patcher.exe

    - name: Attach to Release
      uses: svenstaro/upload-release-action@v2
      with:
        file: randomprime_patcher-${{ env.RELEASE_VERSION }}.zip
        tag: ${{ github.ref }}
        overwrite: true
