name: Python Package

on:
  push:
    branches:
     - main
    tags:
      - '*'
  workflow_dispatch:

  merge_group:
  pull_request:
    branches:
      - main

jobs:

  arm:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Compile in ARM environment
      uses: pguyot/arm-runner-action@v2
      with:
        cpu: cortex-a53
        base_image: raspios_lite_arm64:2022-01-28
        cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
        image_additional_mb: 8192
        commands: |
          #curl -fsSL https://get.docker.com -o get-docker.sh
          #sh ./get-docker.sh
          #docker --version
          #dockerd -H unix:///var/run/docker.sock
          #docker run --name manylinux -d -it quay.io/pypa/manylinux2014_aarch64
          #alias de='docker exec -it manylinux'

          # Install Rust
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup --version

          # Add PPC target
          rustup target add --toolchain stable powerpc-unknown-linux-gnu

          # Add PPA for older python versions and install python 3.8
          apt-get update
          apt-get install -y software-properties-common
          add-apt-repository ppa:deadsnakes/ppa
          apt-get update
          apt-get install python3.8

          # Create venv, update pip, install packages
          python3.8 -m venv .venv
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/python -m pip install --upgrade build auditwheel

          # Build wheel
          .venv/bin/python -m build

          

          

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'macos-12'
          - 'windows-latest'

    runs-on: ${{ matrix.os }}
    name: Wheel for ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Add powerpc-unknown-linux-gnu
        run: rustup target add --toolchain stable powerpc-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2.7.0
      
      - name: Build wheels
        run: pipx run cibuildwheel==2.14.1 --output-dir dist
        env:
          CIBW_BUILD: 'cp38-*'
          CIBW_SKIP: '*-win32 *-manylinux_i686'

      - name: Check if there are changes
        run: git diff --exit-code

      - name: Store the packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist

  linux-build:
    runs-on: ubuntu-latest
    container: ghcr.io/pyca/cryptography-manylinux2014:x86_64
    name: Wheel for Linux
    env:
      RUSTUP_HOME: /root/.rustup

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Avoid issues with Git's solution for CVE-2022-24765 breaking setuptools-scm
        run: git config --global --add safe.directory $(pwd)

      - name: Add powerpc-unknown-linux-gnu
        run: rustup target add --toolchain stable powerpc-unknown-linux-gnu

      - uses: Swatinem/rust-cache@v2.7.0

      - run: /opt/python/cp38-cp38/bin/python -m venv .venv
     
      - name: Update pip
        run: .venv/bin/python -m pip install --upgrade pip

      - name: Install Python packages
        run: .venv/bin/python -m pip install --upgrade build auditwheel

      - name: build wheel
        run: .venv/bin/python -m build

      - name: multilinux stuff
        run: |
          .venv/bin/python -m auditwheel repair --plat manylinux2014_x86_64 dist/*-linux_x86_64.whl -w dist
          rm dist/*-linux_x86_64.whl

      - name: Check if there are changes
        run: git diff --exit-code

      - name: Store the packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist

  test:
    needs:
      - build
      - linux-build
      
    runs-on: ${{ matrix.os.image }}
    name: ${{ matrix.os.name }} - Test Python ${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - {name: 'macOS', image: 'macos-latest', wheel: 'macosx_*'}
          - {name: 'Windows', image: 'windows-latest', wheel: 'win_amd64'}
          - {name: 'Linux', image: 'ubuntu-latest', wheel: 'manylinux_2_17_x86_64.manylinux2014_x86_64'}
        python:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
            
      - name: Install Python packages
        run: python -m pip install --upgrade pip pytest

      - name: install built wheel
        run: python -m pip install dist/*-${{ matrix.os.wheel }}.whl
        shell: bash

      - name: test
        run: python -m pytest
        working-directory: test

  pypi:
    runs-on: 'ubuntu-latest'
    needs:
      - test

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish 📦 to TestPyPI
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.testpypi_password }}
          repository-url: https://test.pypi.org/legacy/
      
      - name: Publish 📦 to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_password }}
